# Generated by Django 6.0.3 on 2026-03-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('exists_since', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HiveMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('co2_level', models.FloatField(help_text='CO2 levels in ppm')),
                ('state', models.CharField(choices=[('QNP', 'QUEEN NOT PRESENT'), ('QPNA', 'QUEEN PRESENT NEWLY ACCEPTED'), ('QPR', 'QUEEN PRESENT AND REJECTED'), ('QPO', 'QUEEEN PRESENT(ORIGINAL)')], max_length=4)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.hive')),
            ],
        ),
    ]
