# Generated by Django 6.0.3 on 2026-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='macaddress',
            field=models.CharField(default='', max_length=17, unique=True),
        ),
    ]
