# Generated by Django 6.0.3 on 2026-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hive_macaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemeasurement',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
