# Generated by Django 6.0.3 on 2026-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hivemeasurement_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivemeasurement',
            name='battery_level',
            field=models.FloatField(default=0, help_text='Battery level in percentage'),
        ),
    ]
