# Generated by Django 6.0.3 on 2026-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hivemeasurement_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivemeasurement',
            name='state',
            field=models.CharField(choices=[('QNP', 'QUEEN NOT PRESENT'), ('QPNA', 'QUEEN PRESENT NEWLY ACCEPTED'), ('QPR', 'QUEEN PRESENT AND REJECTED'), ('QPO', 'QUEEEN PRESENT(ORIGINAL)'), ('SNE', 'script not executed')], max_length=4),
        ),
    ]
